---
Description: CSIP-AUS Client Test Procedures
Version: 0.1
TestProcedures:
  ALL-01:
    Description: Discovery with Out-of-Band Registration
    Category: Registration
    Classes:
      - A
      - DR-A
    Preconditions:
      db: config/preconditions/ALL-01.sql
    Steps:
      ALL-01-001:
        listener-enabled: true
        event:
          type: request-received
          parameters:
            endpoint: /dcap
        actions:
          - action: enable-listeners
            parameters:
              listeners:
                - ALL-01-002
                - ALL-01-003
                - ALL-01-004
          - action: remove-listeners
            parameters:
              listeners:
                - ALL-01-001
      ALL-01-002:
        listener-enabled: false
        event:
          type: request-received
          parameters:
            endpoint: /edev
        actions:
          - action: enable-listeners
            parameters:
              listeners:
                - ALL-01-002
                - ALL-01-003
                - ALL-01-004
          - action: remove-listeners
            parameters:
              listeners:
                - ALL-01-002
      ALL-01-003:
        listener-enabled: false
        event:
          type: request-received
          parameters:
            endpoint: /tm
        actions:
          - action: enable-listeners
            parameters:
              listeners:
                - ALL-01-002
                - ALL-01-003
                - ALL-01-004
          - action: remove-listeners
            parameters:
              listeners:
                - ALL-01-003
      ALL-01-004:
        listener-enabled: false
        event:
          type: request-received
          parameters:
            endpoint: /edev/1/der
        actions:
          - action: enable-listeners
            parameters:
              listeners:
                - ALL-01-002
                - ALL-01-003
                - ALL-01-004
          - action: remove-listeners
            parameters:
              listeners:
                - ALL-01-004
